name: Code Coverage
run-name: Code Coverage ğŸ“Š
on: [push, pull_request]
jobs:
  build_and_test_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Installing
        run: npm install
      - name: testing coverage
        id: test
        run: npm run test-coverage
      - name: Results
        run: echo steps.test.outputs
