name: Lint and Format check
run-name: Lint and Format ğŸ’…ğŸ» âœ”ï¸
on: [push, pull_request]
jobs:
  lint_and_format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo " ğŸ” Checking code --> npm run lint and format"
      - run: |
          npm run lint
          npm run format
      - run: echo "ğŸ This job's status is ${{ job.status }}."
